### ISSUE TITLE
Using Orthographic camera on multiple scens not working

### ISSUE THREAD

**Issue by BenjaminLind04** [defold/codepad#9] opened 2019-11-03 20:17 UTC
When building the project it is complaining about scripts that are not defined, but they are. It also say this: orthographic.camera:519: attempt to index field '?' (a nil value)
Hope you can help me

**Comment by BenjaminLind04** [comment] 2019-11-03 20:33
When building the project it is complaining on scripts that are defined. It also say this: `orthographic.camera:519: attempt to index field '?' (a nil value)` 
Hope you can help me

**Comment by britzl** [comment] 2019-11-03 21:05
Can you please provide a link to a full project where this can be reproduced? It's hard to tell what's wrong without a repro case.

**Comment by BenjaminLind04** [comment] 2019-11-03 21:09
Of corse here it is
[To repo](https://github.com/HelloWorldSweden/Codepad-Crush_Candy)

**Comment by britzl** [comment] 2019-11-06 10:04
I'm unable to reproduce using that example. I see other problems in the browser console that probably needs to be fixed first. Moving this to private chat. Closing.

**Closed by britzl** 2019-11-06 10:04 UTC
